/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.userInterface_generated;

import java.awt.MouseInfo;
import java.awt.Point;

/**
 *
 * @author Esteban Kuh
 */
public class MainJPanel extends javax.swing.JFrame {
    int x,y;
    /**
     * Creates new form MainJPanel
     */
    public MainJPanel() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        panel1 = new org.edisoncor.gui.panel.Panel();
        titleViewLabelMetric = new org.edisoncor.gui.label.LabelMetric();
        priorityButton = new org.edisoncor.gui.button.ButtonAeroRound();
        priorityDfButton = new org.edisoncor.gui.button.ButtonAeroRound();
        sjfButton = new org.edisoncor.gui.button.ButtonAeroRound();
        srtfButton = new org.edisoncor.gui.button.ButtonAeroRound();
        rrButton = new org.edisoncor.gui.button.ButtonAeroRound();
        exitIconPanel = new org.edisoncor.gui.panel.Panel();
        exitButton = new org.edisoncor.gui.button.ButtonAeroRight();
        titleLabel = new org.edisoncor.gui.label.LabelCustom();
        minimiceButton = new org.edisoncor.gui.button.ButtonAero();
        soIconPanel1 = new org.edisoncor.gui.panel.Panel();
        fcfsButton = new org.edisoncor.gui.button.ButtonAeroRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleViewLabelMetric.setBackground(new java.awt.Color(234, 230, 230));
        titleViewLabelMetric.setForeground(new java.awt.Color(226, 226, 226));
        titleViewLabelMetric.setText("Algoritmos de Planificación");
        titleViewLabelMetric.setColorDeSombra(new java.awt.Color(153, 153, 153));
        titleViewLabelMetric.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N

        priorityButton.setBackground(new java.awt.Color(204, 204, 255));
        priorityButton.setForeground(new java.awt.Color(0, 0, 0));
        priorityButton.setText("PRIORIDAD");

        priorityDfButton.setBackground(new java.awt.Color(204, 204, 255));
        priorityDfButton.setForeground(new java.awt.Color(0, 0, 0));
        priorityDfButton.setText("PRIORIDAD DF");

        sjfButton.setBackground(new java.awt.Color(204, 204, 255));
        sjfButton.setForeground(new java.awt.Color(0, 0, 0));
        sjfButton.setText("SJF");

        srtfButton.setBackground(new java.awt.Color(204, 204, 255));
        srtfButton.setForeground(new java.awt.Color(0, 0, 0));
        srtfButton.setText("SRTF");

        rrButton.setBackground(new java.awt.Color(204, 204, 255));
        rrButton.setForeground(new java.awt.Color(0, 0, 0));
        rrButton.setText("RR");

        exitIconPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/icons/icon_logout.png"))); // NOI18N

        javax.swing.GroupLayout exitIconPanelLayout = new javax.swing.GroupLayout(exitIconPanel);
        exitIconPanel.setLayout(exitIconPanelLayout);
        exitIconPanelLayout.setHorizontalGroup(
            exitIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        exitIconPanelLayout.setVerticalGroup(
            exitIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        exitButton.setBackground(new java.awt.Color(204, 204, 255));
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("Exit");

        titleLabel.setBackground(new java.awt.Color(102, 102, 102));
        titleLabel.setForeground(new java.awt.Color(204, 204, 255));
        titleLabel.setText("Sistemas Operativos");
        titleLabel.setFocusable(false);
        titleLabel.setOpaque(true);
        titleLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleLabelMouseDragged(evt);
            }
        });
        titleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleLabelMousePressed(evt);
            }
        });

        minimiceButton.setText("_");
        minimiceButton.setFocusable(false);
        minimiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimiceButtonActionPerformed(evt);
            }
        });

        soIconPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/icons/icon_so.png"))); // NOI18N

        javax.swing.GroupLayout soIconPanel1Layout = new javax.swing.GroupLayout(soIconPanel1);
        soIconPanel1.setLayout(soIconPanel1Layout);
        soIconPanel1Layout.setHorizontalGroup(
            soIconPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        soIconPanel1Layout.setVerticalGroup(
            soIconPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        fcfsButton.setBackground(new java.awt.Color(204, 204, 255));
        fcfsButton.setForeground(new java.awt.Color(0, 0, 0));
        fcfsButton.setText("FCFS");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 96, Short.MAX_VALUE)
                .addComponent(titleViewLabelMetric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(soIconPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sjfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priorityDfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priorityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(srtfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fcfsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121)
                        .addComponent(exitIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minimiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(minimiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(soIconPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleViewLabelMetric, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fcfsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(priorityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(priorityDfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sjfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srtfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void titleLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleLabelMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_titleLabelMousePressed

    private void titleLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleLabelMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_titleLabelMouseDragged

    private void minimiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimiceButtonActionPerformed
        setExtendedState(ICONIFIED); 
    }//GEN-LAST:event_minimiceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.edisoncor.gui.button.ButtonAeroRight exitButton;
    private org.edisoncor.gui.panel.Panel exitIconPanel;
    public org.edisoncor.gui.button.ButtonAeroRound fcfsButton;
    public org.edisoncor.gui.button.ButtonAero minimiceButton;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    public org.edisoncor.gui.button.ButtonAeroRound priorityButton;
    public org.edisoncor.gui.button.ButtonAeroRound priorityDfButton;
    public org.edisoncor.gui.button.ButtonAeroRound rrButton;
    public org.edisoncor.gui.button.ButtonAeroRound sjfButton;
    private org.edisoncor.gui.panel.Panel soIconPanel1;
    public org.edisoncor.gui.button.ButtonAeroRound srtfButton;
    private org.edisoncor.gui.label.LabelCustom titleLabel;
    private org.edisoncor.gui.label.LabelMetric titleViewLabelMetric;
    // End of variables declaration//GEN-END:variables
}
